version: '3'

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=security@gno.land"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  www:
    image: ghcr.io/gnolang/www.gno.land
    build:
      dockerfile: ./Dockerfile
    command: --bind 0.0.0.0:8888 --with-analytics
    ports:
      - 127.0.0.1:8888:8888 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`gno.land`) || Host(`www.gno.land`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
